version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: ./vue-project
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - backend
    networks:
      - project-network
    volumes:
      - ./vue-project/src:/app/src  # Mount local app directory into the container

  backend:
    container_name: backend
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./flask-backend:/app
      - backend-data:/app  # Mount volume for SQLite data
    ports:
      - 5001:5000
    networks:
      - project-network

  testing:
    container_name: testing
    restart: always
    build:
      context: ./testing
      dockerfile: Dockerfile
    depends_on:
      - frontend
    networks:
      - project-network

networks:
  project-network:

volumes:
  backend-data:
