name: Build - CD (Continuous Delivery)

on:
  push:
    branches: [ "main" ]

jobs:

  build-push:
    name: Build and Push Image To DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push flask-backend
        uses: docker/build-push-action@v4
        with:
            context: ./flask-backend
            file: ./flask-backend/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend:${{ github.run_number }}
          
      - name: Build and push tweet-vue
        uses: docker/build-push-action@v4
        with:
            context: ./postgres
            file: ./vue-project/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/vue-project:${{ github.run_number }}
            
