name: Build and Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    

jobs:

  build-push:
    name: Build and Push Image To DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push flask-backend
        uses: docker/build-push-action@v4
        with:
            context: ./flask-backend
            file: ./flask-backend/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend:${{ github.run_number }}
          
      - name: Build and push tweet-vue
        uses: docker/build-push-action@v4
        with:
            context: ./vue-project
            file: ./vue-project/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/vue-project:${{ github.run_number }}
        env:
          VITE_FLASK_API_BASEURL: ${{ env.API_BASE_URL }}

  deploy: 
      name: Deploy to Server
      runs-on: self-hosted
      needs: build-push
      
      steps:
          - name : Pull newest images
            run: |
                docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend:${{ github.run_number }}
                docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vue-project:${{ github.run_number }}
      
          - name: Stop and Remove Existing Containers and Networks
            run: |
                docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
                docker network prune -f

          - name: Create Network and Run containers
            run : |
              docker network create project-network
              docker run -d -p 5000:5000 --network project-network --name flask-backend ${{ secrets.DOCKERHUB_USERNAME }}/flask-backend:${{ github.run_number }}
              sleep 5
              docker run -d -p 8080:8080 --network project-network --name vue-project -e VITE_FLASK_API_BASEURL=http://103.27.206.66:5000 ${{ secrets.DOCKERHUB_USERNAME }}/vue-project:${{ github.run_number }}
      
          - name: Remove unused data
            run: |
              docker system prune -af
